version: '1.0'

services:
  sinapsa.gol.distorleansproc:
    image: ${DOCKER_REGISTRY-}sinapsagoldistorleansproc
    build:
      context: .
      dockerfile: Sinapsa.GoL.DistOrleansProc/Dockerfile
    ports:
      - 5050:5050
    deploy:
      resources:
        limits:
          cpus: 500m
          memory: 200M
        reservations:
          cpus: 25m
          memory: 20M
      