services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  
  redis-insight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    environment:
      RI_REDIS_HOSTS: 'redis'
    depends_on:
      - redis

  gol-backend:
    image: ${DOCKER_REGISTRY-}gol-backend
    build:
      context: .
      dockerfile: Sinapsa.GoL.DistOrleansProc/Dockerfile
    ports:
      - "5050:5050"
    environment:
      ConnectionStrings__redis: redis:6379,abortConnect=false
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 200M
        reservations:
          cpus: 0.025
          memory: 20M

  gol-frontend:
    image: ${DOCKER_REGISTRY-}gol-frontend
    build:
      context: ./frontend/gol-visualizer
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - gol-backend
      